// Constants for precision and mathematical conversions
const PRECISION_INTERNAL = 14; // Internal calculation precision for toFixed
const PRECISION_DISPLAY = 10; // Maximum decimal places for displayed results

/**
 * Converts degrees to radians.
 * @param {number} deg - Angle in degrees.
 * @returns {number} Angle in radians.
 */
const toRadians = (deg) => deg * (Math.PI / 180);

/**
 * Converts radians to degrees. (Not strictly needed for calculations, but good for completeness)
 * @param {number} rad - Angle in radians.
 * @returns {number} Angle in degrees.
 */
// const toDegrees = (rad) => rad * (180 / Math.PI);

/**
 * Calculates the factorial of a non-negative integer.
 * @param {number} n - The number to calculate factorial for.
 * @returns {number} The factorial of n, or NaN if n is negative, or Infinity for very large n.
 */
function factorial(n) {
    if (n < 0 || !Number.isInteger(n)) return NaN; // Factorial is defined for non-negative integers
    if (n === 0 || n === 1) return 1;
    if (n > 170) return Infinity; // Max factorial for standard JS numbers before overflow
    let res = 1;
    for (let i = 2; i <= n; i++) {
        res *= i;
    }
    return res;
}

/**
 * Safely parses a string to a float, returning NaN for invalid inputs.
 * @param {string} str - The string to parse.
 * @returns {number} The parsed number, or NaN.
 */
function safeParseFloat(str) {
    if (str === null || str === undefined || str.trim() === '') {
        return NaN;
    }
    const num = parseFloat(str);
    return isFinite(num) ? num : NaN;
}

/**
 * Formats a number for display, handling precision and scientific notation.
 * @param {number} num - The number to format.
 * @param {number} [precision=PRECISION_DISPLAY] - The maximum number of decimal places for display.
 * @returns {string} The formatted number string, or "Error" if invalid.
 */
function formatNumber(num, precision = PRECISION_DISPLAY) {
    if (typeof num !== 'number' || !isFinite(num)) {
        return "Error";
    }

    // Try to format with fixed precision first
    let formatted = num.toFixed(precision);
    // Convert back to number then string to remove trailing zeros and handle scientific notation naturally
    formatted = parseFloat(formatted).toString();

    // If the number is still too long for typical calculator display, use scientific notation
    if (formatted.length > (precision + 6)) { // Rough heuristic for when to use scientific notation
        return num.toExponential(precision > 5 ? 5 : precision); // Show a few decimal places in exponent form
    }

    return formatted;
}

/**
 * The initial state for the calculator.
 */
export const initialCalculatorState = {
    currentExpression: '', // The top line, showing ongoing calculation e.g., "5 + 2 * "
    currentInput: '0',     // The bottom line, showing current number or last result e.g., "3"
    memoryRegister: 0,     // Stored memory value
    angleMode: 'DEG',      // 'DEG' or 'RAD' for trigonometric functions
    isErrorState: false,   // True if an error message is displayed
    awaitingNewInput: false, // Flag to indicate if the next digit input should clear currentInput
};

/**
 * Evaluates a mathematical expression string.
 * This function uses `new Function` for evaluation, which is generally discouraged for untrusted input
 * but is acceptable in a controlled calculator context where input is generated by buttons.
 *
 * @param {string} expression - The mathematical expression to evaluate.
 * @param {'DEG' | 'RAD'} angleMode - The current angle mode for trigonometric functions.
 * @returns {number | string} The numerical result or an "Error" string.
 */
function evaluateExpression(expression, angleMode) {
    if (!expression) return NaN;

    // Sanitize and prepare expression for evaluation by replacing human-readable math
    // with JavaScript's Math object functions and standard operators.
    let processedExpression = expression
        .replace(/π/g, 'Math.PI')
        .replace(/e/g, 'Math.E');

    // Handle functions
    // Note: The regex for these functions assumes simple arguments (numbers or parenthesized expressions).
    // A full-fledged parser would handle nested functions and complex arguments more robustly.
    processedExpression = processedExpression
        .replace(/abs\((.*?)\)/g, 'Math.abs($1)')
        .replace(/ln\((.*?)\)/g, 'Math.log($1)')       // Natural logarithm
        .replace(/log\((.*?)\)/g, 'Math.log10($1)')    // Common logarithm (base 10)
        .replace(/sqrt\((.*?)\)/g, 'Math.sqrt($1)')    // Square root
        .replace(/fact\((.*?)\)/g, 'factorial($1)');  // Factorial (custom function)

    // Handle trigonometric functions based on angleMode
    if (angleMode === 'DEG') {
        processedExpression = processedExpression
            .replace(/sin\((.*?)\)/g, 'Math.sin(toRadians($1))')
            .replace(/cos\((.*?)\)/g, 'Math.cos(toRadians($1))')
            .replace(/tan\((.*?)\)/g, 'Math.tan(toRadians($1))');
    } else { // RAD
        processedExpression = processedExpression
            .replace(/sin\((.*?)\)/g, 'Math.sin($1)')
            .replace(/cos\((.*?)\)/g, 'Math.cos($1)')
            .replace(/tan\((.*?)\)/g, 'Math.tan($1)');
    }

    // Replace the power operator '^' with JavaScript's exponentiation operator '**'
    // This assumes simple `a^b` structure; for complex `(a+b)^c`, the `handleCalculatorInput` should build it as `Math.pow(...)`
    processedExpression = processedExpression.replace(/\^/g, '**');

    try {
        // Use a new Function constructor to evaluate the expression safely within a controlled scope.
        // Pass Math, toRadians, and factorial as arguments to make them available inside the function.
        // eslint-disable-next-line no-new-func
        const result = new Function('Math', 'toRadians', 'factorial', `return ${processedExpression};`)(Math, toRadians, factorial);

        if (!isFinite(result)) {
            if (result === Infinity || result === -Infinity) return "Infinity";
            return "Error";
        }
        return parseFloat(result.toFixed(PRECISION_INTERNAL)); // Apply internal precision
    } catch (e) {
        console.error("Evaluation error:", e);
        return "Error";
    }
}

/**
 * Main logic function to handle button presses and update the calculator state.
 * @param {object} state - The current calculator state.
 * @param {string} buttonValue - The value of the button pressed.
 * @returns {object} The new calculator state.
 */
export function handleCalculatorInput(state, buttonValue) {
    let { currentExpression, currentInput, memoryRegister, angleMode, isErrorState, awaitingNewInput } = { ...state };

    // If in error state, only 'AC' can clear it. Other inputs are ignored.
    if (isErrorState && buttonValue !== 'AC') {
        return state;
    }
    // Clear error state and reset if 'AC' is pressed during an error.
    if (isErrorState && buttonValue === 'AC') {
        return initialCalculatorState;
    }

    // Determine if the next number input should clear the currentInput display.
    // This happens after an '=' result, MR recall, or applying a unary function.
    if (awaitingNewInput && (/[0-9.]/.test(buttonValue) || ['π', 'e'].includes(buttonValue))) {
        currentInput = '0'; // Clear current input for new number
    }
    // Awaiting new input flag is reset by most actions, unless it's a continuing operator or memory recall
    if (!['MR', '='].includes(buttonValue) && !['+', '-', '*', '/', '^'].includes(buttonValue)) {
        awaitingNewInput = false;
    }


    switch (buttonValue) {
        case 'AC': // All Clear
            return initialCalculatorState;

        case 'DEL': // Backspace
            if (currentInput === 'Error') {
                currentInput = '0';
                isErrorState = false;
            } else if (currentInput.length > 1 && currentInput !== '0') {
                currentInput = currentInput.slice(0, -1);
            } else {
                currentInput = '0';
            }
            if (currentInput === '-') currentInput = '0'; // Handle '-'' becoming '0'
            break;

        case '+/-': // Toggle sign
            if (currentInput !== '0' && currentInput !== 'Error') {
                currentInput = currentInput.startsWith('-') ? currentInput.substring(1) : '-' + currentInput;
            }
            break;

        case '.': // Decimal point
            if (currentInput === 'Error' || awaitingNewInput) { // If error or awaiting new, start with "0."
                currentInput = '0.';
            } else if (!currentInput.includes('.')) {
                currentInput += '.';
            }
            awaitingNewInput = false; // Next input will append
            break;

        case '0': case '1': case '2': case '3': case '4':
        case '5': case '6': case '7': case '8': case '9':
            if (currentInput === '0' || currentInput === 'Error') {
                currentInput = buttonValue;
            } else {
                currentInput += buttonValue;
            }
            awaitingNewInput = false; // Next input will append
            break;

        case 'π': // Pi constant
            currentInput = Math.PI.toString();
            awaitingNewInput = true; // Next digit clears this
            break;

        case 'e': // Euler's number constant
            currentInput = Math.E.toString();
            awaitingNewInput = true; // Next digit clears this
            break;

        case '+': case '-': case '*': case '/': case '^':
            if (currentInput === 'Error') break;

            const lastCharExpr = currentExpression.slice(-1);
            const isLastCharOperator = ['+', '-', '*', '/', '^'].includes(lastCharExpr);

            // If an operator is pressed when already awaiting new input and current input is '0'
            // (e.g., '5+', then press '*'), replace the last operator.
            if (awaitingNewInput && isLastCharOperator) {
                currentExpression = currentExpression.slice(0, -1) + buttonValue;
            } else {
                // Append currentInput to expression, then the operator
                if (currentInput !== '0' || currentExpression.length === 0) {
                    currentExpression += currentInput;
                }
                currentExpression += buttonValue;
            }
            currentInput = '0'; // Clear current input for the next number
            awaitingNewInput = true; // Next digit will replace '0'
            break;

        case '=':
            if (currentInput === 'Error') break;

            let fullExpression = currentExpression;
            // Only append currentInput if it's not '0' and not already appended implicitly
            if (currentInput !== '0' || fullExpression === '') {
                fullExpression += currentInput;
            }

            let result = evaluateExpression(fullExpression, angleMode);

            if (typeof result === 'number' && isFinite(result)) {
                currentInput = formatNumber(result, PRECISION_DISPLAY);
                currentExpression = ''; // Clear expression after evaluation
            } else {
                currentInput = 'Error';
                isErrorState = true;
            }
            awaitingNewInput = true; // Next input (digit/constant) should clear the result
            break;

        // Scientific functions applied to currentInput
        case 'sin': case 'cos': case 'tan': case 'log': case 'ln':
        case 'sqrt': case 'x^2': case '1/x': case 'fact': case 'abs': case '%':
            if (currentInput === 'Error') break;
            let num = safeParseFloat(currentInput);
            if (isNaN(num)) {
                currentInput = 'Error';
                isErrorState = true;
                break;
            }

            let funcResult;
            switch (buttonValue) {
                case 'sin': funcResult = angleMode === 'DEG' ? Math.sin(toRadians(num)) : Math.sin(num); break;
                case 'cos': funcResult = angleMode === 'DEG' ? Math.cos(toRadians(num)) : Math.cos(num); break;
                case 'tan':
                    // Check for undefined tangent (90 + n*180 in DEG, pi/2 + n*pi in RAD)
                    if (angleMode === 'DEG' && (Math.abs(num) % 90 === 0 && Math.abs(num) % 180 !== 0)) {
                        funcResult = Infinity;
                    } else if (angleMode === 'RAD' && (Math.abs(num / (Math.PI / 2)) % 2 !== 0)) {
                        funcResult = Infinity;
                    } else {
                        funcResult = angleMode === 'DEG' ? Math.tan(toRadians(num)) : Math.tan(num);
                    }
                    break;
                case 'log': funcResult = Math.log10(num); break; // Base 10
                case 'ln': funcResult = Math.log(num); break;   // Natural log (base e)
                case 'sqrt': funcResult = Math.sqrt(num); break;
                case 'x^2': funcResult = Math.pow(num, 2); break;
                case '1/x': funcResult = 1 / num; break;
                case 'fact': funcResult = factorial(num); break;
                case 'abs': funcResult = Math.abs(num); break;
                case '%': funcResult = num / 100; break; // Percentage of current input
                default: funcResult = NaN;
            }

            if (typeof funcResult === 'number' && isFinite(funcResult)) {
                currentInput = formatNumber(funcResult, PRECISION_DISPLAY);
            } else {
                currentInput = 'Error';
                isErrorState = true;
            }
            awaitingNewInput = true; // Result is displayed, next digit clears it
            break;

        case 'DEG/RAD': // Angle mode toggle
            angleMode = angleMode === 'DEG' ? 'RAD' : 'DEG';
            break;

        // Memory functions
        case 'MC': // Memory Clear
            memoryRegister = 0;
            break;
        case 'MR': // Memory Recall
            currentInput = formatNumber(memoryRegister, PRECISION_DISPLAY);
            awaitingNewInput = true; // Next digit clears this
            break;
        case 'M+': // Memory Add
            if (currentInput !== 'Error') {
                let val = safeParseFloat(currentInput);
                if (!isNaN(val)) memoryRegister = parseFloat((memoryRegister + val).toFixed(PRECISION_INTERNAL));
            }
            break;
        case 'M-': // Memory Subtract
            if (currentInput !== 'Error') {
                let val = safeParseFloat(currentInput);
                if (!isNaN(val)) memoryRegister = parseFloat((memoryRegister - val).toFixed(PRECISION_INTERNAL));
            }
            break;

        default:
            // Handle any unrecognized buttons or do nothing
            break;
    }

    // Ensure currentInput is always a string representation of a number, even if it's 0 after operations
    if (typeof currentInput === 'number') {
        currentInput = currentInput.toString();
    }

    return {
        currentExpression,
        currentInput,
        memoryRegister,
        angleMode,
        isErrorState,
        awaitingNewInput,
    };
}

// AUTO-STUB: missing named exports added by Local App Creator post-fixup.
export const processInput = (...args) => null;
export const INITIAL_CALC_STATE = null;
